### ISSUE TITLE
issue with documentation

### ISSUE THREAD

**Issue by nicholasjhorton** [c1araaa/ElevatorsNYC#1]
Can you try removing the space between "Elevators" and "NYC" on this line:

#' "Elevators NYC"

https://github.com/c1araaa/ElevatorsNYC/blob/master/R/ElevatorsNYC.R

**Comment by c1araaa** [comment]
I removed the space and I still get this warning message: 
`> checking for missing documentation entries ... WARNING
  Undocumented code objects:
    ‘ElevatorsNYC’
  Undocumented data sets:
    ‘ElevatorsNYC’
  All user-level objects in a package should have documentation entries.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.`
