### ISSUE TITLE
suggest you delete hello.R

### ISSUE THREAD

**Issue by nicholasjhorton** [c1araaa/ElevatorsNYC#2]
https://github.com/c1araaa/ElevatorsNYC/blob/master/R/hello.R

And rebuild your documentation (click on "Settings" on the Build tab).

**Comment by c1araaa** [comment]
@nicholasjhorton, I deleted the hello.R file. I am looking for a "Settings" option under the Build tab and I cannot seem to find it! The only options I see are: 
<img width="271" alt="Screen Shot 2020-11-02 at 2 46 45 PM" src="https://user-images.githubusercontent.com/44950526/97912042-3d50e900-1d1a-11eb-9e59-5efa450b6bbc.png">

**Comment by nicholasjhorton** [comment]
That's the build menu.  Is there a build tab in your project?

But "Configure" should do the trick.

Nick

**Comment by c1araaa** [comment]
Yes! I do have a Build tab in my project and it has the same options as the Build menu. 
<img width="562" alt="Screen Shot 2020-11-02 at 2 50 29 PM" src="https://user-images.githubusercontent.com/44950526/97912395-c1a36c00-1d1a-11eb-984a-0f3773b72ae9.png">
Once I click "configure," I am a little confused about how I can "rebuild my documentation". 
<img width="584" alt="Screen Shot 2020-11-02 at 2 51 24 PM" src="https://user-images.githubusercontent.com/44950526/97912497-e697df00-1d1a-11eb-95f9-b7811a653ffd.png">
I appreciate all the help you are giving me! Thanks Nick!
